paviliondev/discourse-custom-wizard

- assets/javascripts/wizard/templates/components/wizard-field-checkbox.hbs
This PR adds `id` attribute to checkboxes, so they are in sync with label's `for` attribute and work as expected.
**Before**
**After**
> set checkbox id for labels work correctly

- assets/javascripts/wizard/components/custom-user-selector.js.es6
When https://github.com/discourse/discourse/pull/7538 gets merged, the `group` option will be replaced with `groupMembersOf`. 
This option is not being used so I thought it will be a good idea to remove it.
> Remove unused group option from custom-user-search

- lib/custom_wizard/builder.rb
- Helps to save topic custom fields internally via `PostCreator`
- These fields are also available in `post_created` and `topic_created` events as opts[:topic_opts] which helps to preprocess custom fields before saving if required.
> improved topic custom fields saving mechanism

- assets/javascripts/wizard/initializers/custom.js.es6
- Discourse now uses `helperContext` to fetch `siteSettings` so this is required to make the components like `tag-chooser` work on the wizard side of things.
Discussed [here](https://meta.discourse.org/t/moving-away-from-discourse-sitesettings-an-upgrading-guide/158977)
> FIX: discourse now uses helperContext to fetch siteSettings on frontend

- assets/javascripts/wizard/components/wizard-composer-editor.js.es6
Discourse doesn't set the dropZone property on the composer which causes the files to be dropped anywhere in the screen. We're confining the dropZone to the composer edit area. This helps isolate composer drop areas to allow multiple independent composers on a single wizard step.
> FIX: confine the wizard composer's dropZone

- assets/javascripts/wizard-custom.js
- assets/javascripts/wizard/lib/user-search.js.es6
We recently merged a Discourse core's PR to replace usages of Ember's debounce and discourseDebounce with a new debounce wrapper. The new wrapper works exactly like Ember's debounce but internally calls "run" when called in test mode.
This PR replaces all usages of other debounce functions with the new wrapper and fallbacks to Ember's debounce for backward-compatibility.
> Use the new discourseDebounce function wrapper.

- assets/stylesheets/wizard/custom/composer.scss
Copied over markdown table css from discourse to ensure table display nicely.
> FIX: table styles for wizard composer preview

- plugin.rb
- views/layouts/wizard.html.erb
https://github.com/discourse/discourse/pull/12359 
This fixes an issue with SCSS compilation on an upcoming core change (see PR above). 
It also fixes a minor deprecation, `Discourse.base_uri` is now `Discourse.base_path`. 
(I hope you don't mind the whitespace changes.)
> Ensure SCSS compilation compatibility with core

- assets/stylesheets/wizard/custom/field.scss
@angusmcleod 
The css expects `.input-area` to be a direct descendant of `.checkbox-field` class. This isn't the case anymore as the `field-validators` contextual component adds an extra div around all the fields.
> FIX: checkbox description alignment

- lib/custom_wizard/action.rb
- lib/custom_wizard/builder.rb
- lib/custom_wizard/template.rb
- serializers/custom_wizard/wizard_step_serializer.rb
- spec/fixtures/wizard.json
Enabled Templating for
- step and field descriptions
- post builder in create topic action
- Run PrettyText on step description after parsing the template otherwise it messes with the templating code.
> Enable templating 

- controllers/custom_wizard/wizard.rb
Issue: Clicking `Maybe Later` on a wizard currently doesn't redirect the user to the site, instead causes 500 error on the server.
Reason: 
We call `final_cleanup!` in the `CustomWizard::WizardController::skip` action. It checks if the wizard is `unfinished?` at some point. 
The following line in `unfinished?` requires the steps to be loaded in the wizard object, which it can't find if the wizard is created using `CustomWizard::Wizard.create`.
https://github.com/paviliondev/discourse-custom-wizard/blob/ceef3f4bc9cd1505ca017ca1c0e54e88415ce08b/lib/custom_wizard/wizard.rb#L151
> FIX: clicking `Maybe Later` was causing 500 error

- assets/javascripts/wizard/initializers/custom-wizard-field.js.es6
- lib/custom_wizard/field.rb
- serializers/custom_wizard/wizard_field_serializer.rb
~~As per https://mehulkar.com/blog/2019/12/ember-octane-default-values/~~
This is particularly important for conditionality. 
- When a step is entered, the initial value of the checkbox is `null` and once its toggled, only then its value becomes `false` or `true`.
- We should always set the default value as `false` because if the user passes on to the next step without touching the checkbox, the value will be equal to `null` hence, `equal to false` condition won't be satisfied.
> DEV: checkbox value should default to false

- assets/javascripts/discourse/initializers/custom-wizard-redirect.js.es6
- assets/javascripts/discourse/lib/wizard-schema.js.es6
`Discourse.SiteSettings` stopped working after ember cli was enabled in core recently.
> FIX: breakage due to core changes(Ember CLI)

- assets/javascripts/discourse/components/custom-field-input.js.es6
- assets/javascripts/discourse/components/wizard-custom-action.js.es6
- assets/javascripts/discourse/components/wizard-mapper-selector.js.es6
- assets/javascripts/discourse/controllers/admin-wizards-custom-fields.js.es6
- assets/javascripts/discourse/lib/wizard.js.es6
- assets/javascripts/discourse/routes/admin-wizards-wizard-show.js.es6
- assets/javascripts/discourse/templates/components/custom-field-input.hbs
- assets/javascripts/discourse/templates/components/wizard-custom-action.hbs
- assets/stylesheets/common/wizard-admin.scss
- config/locales/client.en.yml
- controllers/custom_wizard/admin/admin.rb
- extensions/custom_field/extension.rb
- lib/custom_wizard/action.rb
- lib/custom_wizard/custom_field.rb
- plugin.rb
- spec/components/custom_wizard/action_spec.rb
- spec/components/custom_wizard/custom_field_spec.rb
- spec/fixtures/wizard.json
- spec/requests/custom_wizard/admin/custom_fields_controller_spec.rb
This PR does a few things to improve our support of custom fields
1. Adds custom fields added by other plugins to the list in admin/wizards/custom-fields and the custom field list in the mapper selector
2. Adds support for json custom fields in the wizard actions
> Add custom field improvements

- controllers/custom_wizard/steps.rb
- lib/custom_wizard/builder.rb
- spec/components/custom_wizard/wizard_spec.rb
- spec/fixtures/wizard.json
The can_access? check will fail if the wizard does not allow multiple submissions. This means that on the second build of the wizard on the final step of a single submission wizard, the wizard instance will have no steps, and an error will be thrown when logic assumes it does.
This was not picked up in our spec because our wizard.json fixture had ``multiple_submissions`` set to ``true``. I've set that to false and tweaked the one test that assumed it was true.
> Force second step build to overcome can_access? check

- assets/stylesheets/common/wizard-admin.scss
- assets/stylesheets/common/wizard-api.scss
- assets/stylesheets/common/wizard-manager.scss
- assets/stylesheets/common/wizard-mapper.scss
- assets/stylesheets/wizard/custom/badges.scss
- assets/stylesheets/wizard/custom/composer.scss
Switches all SCSS color variables to CSS custom properties. This is to future-proof the plugin to changes in how plugin stylesheets are going to be compiled in core (plus it has better support for automatic dark mode).
> DEV: Switch to CSS custom properties for colors

- assets/javascripts/wizard/initializers/custom-wizard.js.es6
- lib/custom_wizard/field.rb
We get `BAD CSRF` errors for some ajax calls in dev. This is not reproducible on production though. This code intercepts all the ajax calls on the wizard side and adds the `X-CSRF-Token` header to them in dev mode.
> FIX: add csrf token to all wizard ajax requests in dev

- spec/components/custom_wizard/wizard_spec.rb
@angusmcleod 
The categories are cached by the `Site` model class. We need to purge the cache so that we fetch the accurate list.
Here's a list of failed workflow runs we've had. The reason IMHO is the sequence of tests. https://github.com/paviliondev/discourse-custom-wizard/actions?query=is%3Afailure+workflow%3Aplugin-tests
> FIX: clear site model cache to prevent spec failure

- spec/plugin_helper.rb
@angusmcleod 
Explaination:
This PR addresses the spec failures we see in [this workflow run](https://github.com/paviliondev/discourse-custom-wizard/runs/3290606534). The reason for failure is, our fixture json contains small strings like`"1"` etc. 
[This discourse commit](https://github.com/discourse/discourse/commit/7ecd0da109e6eae87b680fb0741f4c19ab8ac08a ) bumps the version of Oj gem which looks safe and harmless.
The Oj gem is used in discourse as a default for parsing json. But that particular version introduces major changes including  **String Caching** for short strings while parsing json to improve overall performance.  In order to cache short strings, it `freeze`s them and hence they become immutable.
When any of those strings are passed to our `Mapper`'s `interpolate` method, …
> FIX: disable string caching in `Oj` gem while running specs

- controllers/custom_wizard/wizard.rb
- lib/custom_wizard/submission.rb
- lib/custom_wizard/wizard.rb
- spec/requests/custom_wizard/wizard_controller_spec.rb
Changes :
-  removes current submission if user skips the wizard.
- resets step progress for the user so that the wizard starts from the first step when user visits next.
> FIX: clear submission if skipped by user

- db/migrate/20210806135416_split_custom_wizard_log_fields.rb
- lib/custom_wizard/action.rb
- lib/custom_wizard/log.rb
- serializers/custom_wizard/log_serializer.rb
- spec/components/custom_wizard/log_spec.rb
- spec/requests/custom_wizard/admin/logs_controller_spec.rb
- spec/serializers/custom_wizard/log_serializer_spec.rb
Split out the wizard, user and action in the message field for custom wizard logs into their own fields.
Includes data migration and updates to saving logs. This has an incidental effect on the log page, which will show the shortened message.
> DEV: split log messages

- lib/custom_wizard/validators/template.rb
- plugin.rb
- spec/components/custom_wizard/template_validator_spec.rb
@angusmcleod 
- Our template validator isn't validating the fields correctly in the backend. The fields are in `step[:fields]`.
- The reason why field validation still works is, we're relying on the frontend code for validating fields and sending frontend errors to backend. Here's the responsible code. https://github.com/paviliondev/discourse-custom-wizard/blob/757b382345c739c9a65fc5888ce322277d99994c/assets/javascripts/discourse/models/custom-wizard.js.es6#L14
- I think in the future, we should tweak the code such that we're only validating on the server. 
- Writing specs for this one now.
> FIX: field validation was not working in backend

- assets/javascripts/discourse/templates/components/wizard-custom-field.hbs
- assets/javascripts/discourse/templates/components/wizard-custom-step.hbs
- plugin.rb
The image-uploader component is deprecated and will
be removed shortly in Discourse core. The new component
is functionally equivalent.
> FIX: Use uppy-image-uploader instead of image-uploader

- assets/javascripts/discourse/components/wizard-mapper-selector.js.es6
- assets/javascripts/discourse/templates/components/wizard-mapper-selector.hbs
- plugin.rb
`{{user-selector}}` has been deprecated since February 2021 and is about to be removed https://github.com/discourse/discourse/commit/293fd1f743b1c8165e1cd06b1169134197a231f7. `{{email-group-user-chooser}}` is the new replacement and this PR migrates the plugin to use this new component. Screenshot of this change in action:
> DEV: Replace `{{user-selector}}` with `{{email-group-user-chooser}}`

- assets/javascripts/discourse/components/custom-wizard-composer-editor.js.es6
- plugin.rb
https://discourse.pluginmanager.org/t/image-upload-button-missing-in-composer-on-mobile-view/584
> Allow upload button in wizard composer when in mobile view

- assets/javascripts/discourse/controllers/admin-wizards-wizard-show.js.es6
- plugin.rb
A patch for the preview Wizard URL path (in admin view) to take account of Discourse deployments with subdirectory base URL i.e. `www.discourse.com/foo/bar`. 
Currently it will present the URL only on the top level domain i.e. `www.discourse.com/w/1234` where it should have included the subdirectories. i.e. `www.discourse.com/foo/bar/w/1234`
> Patch for wizard URL path to take account of subdirectory base URL.

- lib/custom_wizard/log.rb
- plugin.rb
- spec/serializers/custom_wizard/log_serializer_spec.rb
* Add the ability to specify a date for the log (default Now) so that order is "testable" in a spec.
> FIX: failing log spec

- assets/javascripts/discourse/controllers/next-session-scheduled.js.es6
- plugin.rb
- test/javascripts/acceptance/admin-wizards-unsuscribed-test.js
* Currently when you create a new wizard the time shows NaN.
> FIX: direct after start time default for new wizard

- lib/custom_wizard/template.rb
- plugin.rb
- spec/requests/custom_wizard/admin/wizard_controller_spec.rb
* Thought we'd fixed this in prior PR (#255) but it fails with multi word wizard names as they are underscored and down cased.
* Take two: now ensure this works with multi-word named wizard
> FIX: Remove category custom field on wizard delete (Take Two)

- assets/javascripts/discourse/components/custom-wizard-composer-editor.js.es6
- plugin.rb
👋 Hi all,
This PR reverts a change in the stable branch that caused errors. The update was needed for the main branch but not for stable.
Additionally, we need to update the CI workflow to test the stable branch of this plugin against Discourse's stable branch. I'll work on this change.
Thanks,
Marcos
> REVERT: Update insert-hyperlink invocation following core change

- assets/javascripts/discourse/initializers/custom-wizard-redirect.js.es6
- plugin.rb
- test/javascripts/acceptance/wizard-test.js
* permits admin to provide links to forum that can open in new tab, without redirecting back to wizard.
* any attempt to navigate forum from there will cause forum to redirect to wizard
> FEATURE: implement a way to temporarily ignore redirect

- assets/javascripts/discourse/initializers/custom-wizard-edits.js.es6
- plugin.rb
- test/javascripts/acceptance/category-chooser-initializer-test.js
This PR introduces a change to the `category-chooser` component to display all categories for admin and staff users. Regular and not-logged-in users will still see the filtered list of categories.
- Added a condition to bypass the category filter for admin and staff users.
> Filter categories for admin staff

- README.md
- assets/javascripts/discourse/mixins/subscription.js.es6
- assets/javascripts/discourse/services/subscription.js
- plugin.rb
Brings Readme into line with current gem subscription situation.
Also changes the destination of the Subscribe button in /admin/wizards/wizard to https://custom-wizard.pavilion.tech/pricing. This reduces a redundant step/click in the subscription flow for users.
> Tweak readme

- assets/javascripts/discourse/components/custom-wizard-step.js.es6
- assets/javascripts/discourse/models/custom-wizard-field.js.es6
- assets/javascripts/discourse/models/custom-wizard-step.js.es6
- assets/javascripts/discourse/models/custom-wizard.js.es6
- assets/javascripts/discourse/routes/custom-wizard.js.es6
- plugin.rb
- test/javascripts/acceptance/wizard-test.js
- test/javascripts/helpers/wizard.js
See further https://meta.discourse.org/t/deprecation-upcoming-removal-of-bootbox-dependency/296160
> Remove bootbox

- lib/custom_wizard/extensions/discourse_tagging.rb
After testing this further, I am convinced that this is the issue (and the solution)
The plugin reuses the for_input tag to designate tags from specific tag groups.
However, core expects that :for_input is used with a category, and if there are tag group restrictions it will honor them.
If :for_input is passed to core without a category, any tags that contain to a tag group that is used in ANY category as a restricted tag group, are not returned.
This makes the plugin unusable for assigning tags from restricted tag groups to a topic.
At the moment CW uses the tag picker, it's not clear to which category the topic is going to be in, so passing the category together with :for_input is not an option.
The only option left to make this work is to remove :for_input.
This behavior is the same in …
> Do not pass :for_input to super if it was used for tag groups

- assets/javascripts/discourse/components/custom-wizard-composer-editor.js
- plugin.rb
- test/javascripts/acceptance/admin-wizards-unsubscribed-test.js
- test/javascripts/acceptance/field-test.js
> Also in this commit I am renaming the InsertHyperlink modal to UpsertHyperlink
Sighs.
> Fix for useless refactor in core 8445eec
