assets/stylesheets/wizard_custom_admin.scss

This should take care of the layout issue mentioned below
https://meta.discourse.org/t/custom-wizard-plugin/73345/272?u=makarygo

Fix for wizard height issue

---

assets/javascripts/wizard/routes/custom.js.es6

Hey Angus, I saw the footer image isn't pulling correctly, so I made a small fix for you. Appears the site setting name changed previously.

Fix missing footer image

---

assets/javascripts/wizard-custom-guest.js
controllers/wizard.rb

javascript based cookie setting and redirect, removed ruby cookie handling

fix redirect after login

---

config/locales/client.pt_br.yml
config/locales/server.en.yml
config/locales/server.pt_br.yml

I have created a client.pt_br.yml and server.pt_br.yml for Brazilian Portuguese translations. Also found a little error in an English file and corrected that.

Translations for Brazilian Portuguese

---

assets/javascripts/discourse/lib/wizard.js.es6
lib/custom_wizard/mapper.rb

Added (and tested) two more user_options columns.

Add email_messages_level and email_digests as updatable user fields

---

assets/javascripts/discourse/mixins/undo-changes.js.es6
assets/javascripts/wizard/lib/user-search.js.es6

Lodash is being removed from core Discourse: https://github.com/discourse/discourse/pull/10566/commits

REFACTOR - remove _.debounce and _.isEqual

---

.github/workflows/plugin-tests.yml

- Use SIMPLECOV=1
- Run Rspec and SimpleCov in the same step

combine rspec run with coverage report

---

assets/javascripts/wizard/components/wizard-date-input.js.es6
assets/javascripts/wizard/templates/components/wizard-field-date.hbs

For https://thepavilion.io/t/date-format-not-respected/4503/10

Apply format to new picker in wizard-date-input

---

assets/javascripts/discourse/controllers/admin-wizards-submissions-show.js.es6
assets/javascripts/discourse/models/custom-wizard.js.es6
assets/javascripts/discourse/routes/admin-wizards-submissions-show.js.es6
assets/javascripts/discourse/templates/admin-wizards-submissions-show.hbs
controllers/custom_wizard/admin/submissions.rb
lib/custom_wizard/submission.rb
lib/custom_wizard/wizard.rb
serializers/custom_wizard/submission_serializer.rb
spec/components/custom_wizard/submission_spec.rb

@keegangeorge Here's the PR adding pagination to submissions that we worked up on the call. I tweaked a few things after our call. Give it a review, and then merge if you're satisfied.

IMPROVE: Admin UI support

---

assets/javascripts/discourse/components/wizard-links.js.es6
assets/javascripts/discourse/templates/components/wizard-links.hbs
plugin.rb

@fzngagan I think we should actually just remove sortable and use manual controls. Users have complained about the sorting behaviour in the past. We then don't have to worry about the dependency, now or in the future.

IMPROVE: Remove sortable and add manual step and field sorting

---

assets/javascripts/wizard/components/wizard-field-upload.js.es6
assets/javascripts/wizard/templates/components/wizard-field-upload.hbs
plugin.rb

Implements uppy.js, the new standard Discourse upload library, in wizard-field-upload.

DEV: Use uppy in upload field

---

plugin.rb
serializers/custom_wizard/wizard_field_serializer.rb

Fix issue with dropdown not working 
#184 
Tested as working

Fix issue with dropdown not working

---

app/controllers/custom_wizard/admin/wizard.rb
app/serializers/custom_wizard/wizard_field_serializer.rb
assets/javascripts/discourse/templates/components/custom-wizard-field-tag.hbs
assets/javascripts/discourse/templates/components/wizard-custom-field.hbs
config/locales/client.en.yml
lefthook.yml
lib/custom_wizard/builder.rb
lib/custom_wizard/field.rb
plugin.rb

@merefield Perhaps @jumagura can review this one? What do you think.

FEATURE: add can_create_tag

---

assets/javascripts/discourse/components/wizard-text-editor.js.es6
lib/custom_wizard/mapper.rb
plugin.rb
spec/components/custom_wizard/mapper_spec.rb
spec/fixtures/mapper/inputs.json

@jumagura If you could please review this one. The context for this is here
https://coop.pavilion.tech/t/custom-wizard-support/1163

Add avatar interpolation support

---

assets/javascripts/discourse/components/wizard-custom-action.js.es6
assets/javascripts/discourse/lib/wizard-schema.js.es6
assets/javascripts/discourse/templates/components/wizard-custom-action.hbs
config/locales/client.en.yml
lib/custom_wizard/action.rb
lib/custom_wizard/subscription.rb
plugin.rb
spec/components/custom_wizard/action_spec.rb
spec/fixtures/actions/watch_tags.json

https://coop.pavilion.tech/t/add-a-watch-tags-action/1334

Add watch tags action

---

assets/stylesheets/common/wizard/step.scss
plugin.rb

FIX: compound selectors may no longer be extended

---

plugin.rb
spec/requests/custom_wizard/admin/manager_controller_spec.rb

FIX: (File|Dir).exists? is deprecated

---

assets/javascripts/discourse/components/custom-wizard-composer-editor.js.es6
assets/javascripts/discourse/mixins/undo-changes.js.es6
plugin.rb

Fixes https://coop.pavilion.tech/t/unable-to-copy-paste-or-upload-image-into-cw-composer/1471

Move to new Uppy handling in discourse/discourse

---

lib/custom_wizard/mapper.rb
plugin.rb
spec/components/custom_wizard/mapper_spec.rb

Fixes https://coop.pavilion.tech/t/accessing-an-upload-field-without-a-property-in-a-template-crashes/1363

Ensure we're not interpolating an object

---

assets/javascripts/discourse/lib/wizard-schema.js.es6
assets/javascripts/discourse/templates/components/wizard-custom-field.hbs
assets/javascripts/discourse/templates/components/wizard-custom-step.hbs
plugin.rb

Adds subscription support to the field type selector.

Add wizard-subscription-selector support to field type selection

---

lib/custom_wizard/subscription.rb
plugin.rb
spec/components/custom_wizard/subscription_spec.rb

Fixes the subscription sort when the instance has multiple active subscriptions.

Fix multiple subscriptions sort

---

lib/custom_wizard/submission.rb
lib/custom_wizard/subscription.rb
plugin.rb
spec/serializers/custom_wizard/submission_serializer_spec.rb

See further https://coop.pavilion.tech/t/discourse-custom-wizard-main-does-not-work-on-tests-passed/3058

FIX: explicitly order submission list for specs

---

assets/javascripts/discourse/components/wizard-mapper-selector.js.es6
assets/javascripts/discourse/initializers/custom-wizard-edits.js.es6
assets/javascripts/discourse/lib/wizard-schema.js.es6
assets/javascripts/discourse/mixins/subscription.js.es6
assets/javascripts/discourse/templates/components/wizard-realtime-validations.hbs
plugin.rb

* Resolves issue where values don't get saved
* Deals with some current deprecations
* Resolves warning about lack of pluginId

FIX:  admin wizard validations form

---

assets/javascripts/discourse/templates/admin-wizards-manager.hbs
assets/javascripts/discourse/templates/components/wizard-table-field.hbs
assets/stylesheets/common/wizard/wizard.scss
plugin.rb
spec/components/custom_wizard/action_spec.rb
spec/requests/custom_wizard/admin/api_controller_spec.rb
test/javascripts/acceptance/admin-custom-fields-unsubscribed-test.js
test/javascripts/acceptance/admin-logs-test.js
test/javascripts/acceptance/admin-submissions-test.js
test/javascripts/acceptance/admin-wizards-api-test.js
test/javascripts/acceptance/admin-wizards-business-subscription-test.js
test/javascripts/acceptance/admin-wizards-standard-subscription-test.js
test/javascripts/acceptance/admin-wizards-unsubscribed-test.js
test/javascripts/acceptance/field-test.js

Internal: https://coop.pavilion.tech/t/addressing-ember-version-in-custom-wizard-plugin-tests/3359

COMPATIBILITY: Support Discourse 3.2

---

assets/javascripts/discourse/initializers/custom-wizard-edits.js.es6
plugin.rb

See https://coop.pavilion.tech/t/custom-wizard-admin-route-not-accessible-with-new-admin-sidebar/3489

Add admin sidebar section link

---

assets/javascripts/discourse/components/custom-wizard-composer-editor.js.es6
assets/javascripts/discourse/components/custom-wizard-step.js.es6
assets/javascripts/discourse/templates/components/custom-wizard-step.hbs
plugin.rb
test/javascripts/acceptance/field-test.js

See further https://coop.pavilion.tech/t/image-upload-in-composer-hitting-next-should-be-greyed-out/3521

FIX: Disable step controls when uploading
